name: metaAI
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.8
  - pytorch >= 1.13
  - torchvision
  - pytorch-cuda=11.7
  - pip:
    - timm#=1.0.3
    - diffusers#=0.27.2
    - accelerate#=0.30.1
    - h5py#=3.9.0
    - einops#=0.8.0
    - einops_exts#=0.0.4
    - beartype#=0.18.5
    - lmdb#=1.4.1
    - numpy==1.26.4
