name: metaAI
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.8
  - pytorch >= 1.13
  - torchvision
  - pytorch-cuda=11.7
  - pip:
    - timm
    - diffusers
    - accelerate
    - h5py
    - einops
    - einops_ext
    - beartype
    - lmdb
    - numpy
